name = "GeoSMP-3"
author = "Wladimir"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58b29c3d3a314fdb72fc03068bcda0ad92eef07a3cb1d4ed7fc9caf5218446a8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
