name = "GeoSMP-3"
author = "Wladimir"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83e844d5988a1fa64e61ee4442ac07b8c15e24ee5cfa0eb24204c147ccbea215"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
