! Put your rules here in the format:
! old_biome > new_biome
! 
! Examples (remove ! in front of one to activate it):
! minecraft:dark_forest > minecraft:cherry_grove
! #minecraft:is_forest > minecraft:desert
#terralith:skylands > null
terralith:lavender_forest > minecraft:forest
terralith:lavender_valley > terralith:blooming_valley
terralith:mirage_isles > minecraft:mushroom_fields
terralith:moonlight_valley > terralith:sakura_valley
terralith:moonlight_grove > nomansland:maple_grove
terralith:amethyst_canyon > minecraft:jungle
terralith:amethyst_rainforest > minecraft:jungle
terralith:painted_mountains > minecraft:badlands
terralith:scarlet_mountains > minecraft:jagged_peaks
terralith:tropical_jungle > minecraft:jungle
terralith:warped_mesa > terralith:white_mesa